/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.SaleDAO;
import helpers.Fecha;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Sale;

/**
 *
 * @author diego
 */
public class SalesReport extends javax.swing.JFrame {

    /**
     * Creates new form SalesReport
     */
    public SalesReport() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stxTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        txtEndDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSearchBetween = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        btnList = new javax.swing.JButton();
        JButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stxTitle.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        stxTitle.setText("Reporte de Ventas");
        jPanel1.add(stxTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jLabel1.setText("Por Fecha:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 30));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        jLabel2.setText("Entre Fechas :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
        jPanel1.add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 90, 30));
        jPanel1.add(txtEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 100, 30));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel3.setText("-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 70, -1, 30));

        btnSearchBetween.setText("Buscar");
        btnSearchBetween.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBetweenActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchBetween, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 80, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 10, 60));

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°Venta", "Cliente", "Artículo", "Valor Neto", "Valor Total", "Fecha Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(salesTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 560, 190));

        btnList.setText("Listar Ventas");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        jPanel1.add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        JButton1.setText("Salir");
        JButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(JButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        DefaultTableModel tm = (DefaultTableModel) salesTable.getModel();
        tm.setNumRows(0);
        int i = 0;
        for (Sale sale : SaleDAO.all()) {
            tm.insertRow(
                    i, new Object[]{
                        sale.getId(),
                        sale.getClient().getName(),
                        sale.getArticle().getName(),
                        sale.getNet(),
                        sale.getTotal(),
                        sale.getSaleAt()
                    });
            i++;
        };


    }//GEN-LAST:event_btnListActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Fecha date = new Fecha(txtDate.getText());
        if (date.fechaCorrecta()) {
            ArrayList<Sale> sales = SaleDAO.findByDate(date);
            if (!sales.isEmpty()) {
                DefaultTableModel tm = (DefaultTableModel) salesTable.getModel();
                tm.setNumRows(0);
                int i = 0;
                for (Sale sale : sales) {
                    tm.insertRow(
                            i, new Object[]{
                                sale.getId(),
                                sale.getClient().getName(),
                                sale.getArticle().getName(),
                                sale.getNet(),
                                sale.getTotal(),
                                sale.getSaleAt()
                            });
                    i++;
                };
                JOptionPane.showMessageDialog(null, "Venta encontrada", "Buscar", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Venta no encontrada", "Buscar", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese una fecha Válida", "Buscar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchBetweenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBetweenActionPerformed
        Fecha startDate = new Fecha(txtStartDate.getText());
        Fecha endDate = new Fecha(txtEndDate.getText());
        if (startDate.fechaCorrecta() && endDate.fechaCorrecta()) {
            ArrayList<Sale> sales = SaleDAO.findBetweenDates(startDate, endDate);
            if (!sales.isEmpty()) {
                DefaultTableModel tm = (DefaultTableModel) salesTable.getModel();
                tm.setNumRows(0);
                int i = 0;
                for (Sale sale : sales) {
                    tm.insertRow(
                            i, new Object[]{
                                sale.getId(),
                                sale.getClient().getName(),
                                sale.getArticle().getName(),
                                sale.getNet(),
                                sale.getTotal(),
                                sale.getSaleAt()
                            });
                    i++;
                };
                JOptionPane.showMessageDialog(null, "Venta encontrada", "Buscar", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Venta no encontrada", "Buscar", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese una fecha Válida", "Buscar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchBetweenActionPerformed

    private void JButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchBetween;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton JButton1;
    private javax.swing.JTable salesTable;
    private javax.swing.JLabel stxTitle;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
