/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import com.sun.glass.events.KeyEvent;
import controllers.ArticleDAO;
import controllers.ClientDAO;
import controllers.SaleDAO;
import helpers.Fecha;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.Article;
import models.Client;
import models.Sale;

/**
 *
 * @author diego
 */
public class SalesForm extends javax.swing.JFrame {

    /**
     * Creates new form SalesForm
     */
    public SalesForm() {
        initComponents();
        setLocationRelativeTo(this);
        fillComboArticles();
        fillComboClients();
    }

    public void fillComboArticles() {
        ArrayList<Article> articles = ArticleDAO.all();
        comboArticles.removeAllItems();
        comboArticles.addItem("Seleccionar");
        articles.forEach((article) -> {
            comboArticles.addItem(article.getName());
        });
    }

    public void fillComboClients() {
        ArrayList<Client> clients = ClientDAO.all();
        comboClients.removeAllItems();
        comboClients.addItem("Seleccionar");
        clients.forEach((article) -> {
            comboClients.addItem(article.getName());
        });
    }

    public void clearForm() {
        txtId.setText("");
        txtDate.setText("");
        comboArticles.setSelectedIndex(0);
        comboClients.setSelectedIndex(0);
        stxName.setText("");
        stxStock.setText("");
        stxPrice.setText("");
        txtQtt.setText("");
        txtNet.setText("");
        txtIva.setText("");
        txtTotal.setText("");
    }

    public void calculatePrice(int qtty) {
        int price = Integer.parseInt(stxPrice.getText()),
                total;
        double iva, net;
        total = qtty * price;
        iva = total * 0.19;
        net = total - iva;
        txtNet.setText(String.valueOf(net));
        txtIva.setText(String.valueOf(iva));
        txtTotal.setText(String.valueOf(total));
    }

    public boolean hasStock() {
        int stock, qtty;
        qtty = Integer.parseInt(txtQtt.getText());
        stock = stxStock.getText().equals("") ? 0 : Integer.parseInt(stxStock.getText());

        return stock != 0 && qtty <= stock;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stxTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboArticles = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        stxName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stxStock = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stxPrice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQtt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        comboClients = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txtDate = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stxTitle.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        stxTitle.setText("Registrar nueva Venta");
        jPanel1.add(stxTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel1.setText("N° Venta :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 57, -1, 20));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 49, 60, 30));

        jLabel3.setText("Seleccionar Artículo :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        comboArticles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        comboArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboArticlesActionPerformed(evt);
            }
        });
        jPanel1.add(comboArticles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, -1));

        jPanel2.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle de artículo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nombre :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));
        jPanel2.add(stxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, 20));

        jLabel6.setText("Stock :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));
        jPanel2.add(stxStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, 20));

        jLabel8.setText("Precio :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));
        jPanel2.add(stxPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 140, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 350, 120));

        jLabel5.setText("Fecha de Venta: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 57, -1, 20));

        jLabel2.setText("Cantidad : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        txtQtt.setEnabled(false);
        txtQtt.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtQttInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtQtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQttActionPerformed(evt);
            }
        });
        txtQtt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQttKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQttKeyReleased(evt);
            }
        });
        jPanel1.add(txtQtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 60, 30));

        jLabel7.setText("Precio Neto :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));
        jPanel1.add(txtNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 100, -1));

        jLabel9.setText("Total IVA :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));
        jPanel1.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 100, -1));

        jLabel10.setText("Precio final Venta :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 100, -1));

        jButton1.setText("Vender");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 90, -1));

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 80, -1));

        jLabel11.setText("Cliente :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        comboClients.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        comboClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClientsActionPerformed(evt);
            }
        });
        jPanel1.add(comboClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 80, -1));

        txtDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboArticlesActionPerformed
        String name;
        Article article = null;
        if (comboArticles.getSelectedItem() != null
                && comboArticles.getSelectedIndex() != 0) {
            txtQtt.setEnabled(true);
            name = String.valueOf(comboArticles.getSelectedItem());
            article = ArticleDAO.findByName(name);
            if (article != null) {
                stxName.setText(article.getName());
                stxStock.setText(String.valueOf(article.getStock()));
                stxPrice.setText(String.valueOf(article.getPrice()));
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error al seleccionar artículo", "Información", 0);
            }
        } else {
            txtQtt.setEnabled(false);
        }
    }//GEN-LAST:event_comboArticlesActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id, qtty, price;
        String d, articleName, clientName;
        Article article = null;
        Client client = null;
        Sale sale = null;
        Fecha date = new Fecha(txtDate.getText());
        if (!txtId.getText().equals("")
                && !txtDate.getText().equals("")
                && date.fechaCorrecta()
                && !stxPrice.getText().equals("")
                && !txtQtt.getText().trim().equals("")
                && Integer.parseInt(txtQtt.getText().trim()) != 0
                && comboClients.getSelectedIndex() != 0
                && hasStock()) {
            id = Integer.parseInt(txtId.getText());
            d = txtDate.getText();
            articleName = String.valueOf(comboArticles.getSelectedItem());
            clientName = String.valueOf(comboClients.getSelectedItem());
            article = ArticleDAO.findByName(articleName);
            client = ClientDAO.findByName(clientName);
            qtty = Integer.parseInt(txtQtt.getText());
            sale = new Sale(id, date, article, client, qtty);
            if(SaleDAO.create(sale)){
                JOptionPane.showMessageDialog(null, "Venta ingresada!", "Venta", 1);
                clearForm();
            }else{
                JOptionPane.showMessageDialog(null, "Error al ingresar venta", "Error", 0);
            }
        } else {
            if (!date.fechaCorrecta()) {
                JOptionPane.showMessageDialog(null, "Ingrese una fecha Válida", "Validación", 0);
            } else if (!hasStock()) {
                JOptionPane.showMessageDialog(null, "Producto sin Stock :\n "
                        + "Solicitado : " + txtQtt.getText() + "\n "
                        + "Stock : " + stxStock.getText(), "Validación", 0);
            }else if (!txtQtt.getText().trim().equals("")
                || Integer.parseInt(txtQtt.getText().trim()) != 0){
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad válida distinta de 0", "Validación", 0);
            }
            else {
                JOptionPane.showMessageDialog(null, "Ingrese todos los datos de la venta", "Validación", 0);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClientsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtQttKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQttKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        int code = evt.getKeyCode();
        int price, qtty = 0;
        if (!(Character.isDigit(c) || code == KeyEvent.VK_BACKSPACE || code == KeyEvent.VK_DELETE)
            || code == KeyEvent.VK_SPACE) {
            getToolkit().beep();
            evt.consume();
        } else {
            if (!txtQtt.getText().trim().equals("")) {
                txtQtt.setText(txtQtt.getText().trim());
                qtty = Integer.parseInt(txtQtt.getText());
                calculatePrice(qtty);
            } else {
                txtNet.setText("");
                txtIva.setText("");
                txtTotal.setText("");
            }
        }
    }//GEN-LAST:event_txtQttKeyReleased

    private void txtQttKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQttKeyPressed

    }//GEN-LAST:event_txtQttKeyPressed

    private void txtQttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQttActionPerformed

    }//GEN-LAST:event_txtQttActionPerformed

    private void txtQttInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtQttInputMethodTextChanged

    }//GEN-LAST:event_txtQttInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> comboArticles;
    private javax.swing.JComboBox<String> comboClients;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel stxName;
    private javax.swing.JLabel stxPrice;
    private javax.swing.JLabel stxStock;
    private javax.swing.JLabel stxTitle;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNet;
    private javax.swing.JTextField txtQtt;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
