/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.UserDAO;
import javax.swing.JOptionPane;
import models.User;

/**
 *
 * @author diego
 */
public class UsersMaintainer extends javax.swing.JFrame {

    /**
     * Creates new form ArticlesMaintainer
     */
    public UsersMaintainer() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public void fillForm(User user) {
        txtUsername.setText(user.getUsername());
        txtFullName.setText(user.getName());
        txtRut.setText(user.getRut());
        txtPassword.setText(user.getPassword());
        txtRepeatPassword.setText(user.getPassword());
        checkLocked.setSelected(user.isLocked());
    }

    public void clearForm() {
        txtUsername.setText("");
        txtFullName.setText("");
        txtRut.setText("");
        txtPassword.setText("");
        txtRepeatPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnListUsers = new javax.swing.JToggleButton();
        btnSearch = new javax.swing.JToggleButton();
        btnDelete = new javax.swing.JToggleButton();
        btnEdit = new javax.swing.JToggleButton();
        btnCreate = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JTextArea();
        txtPassword = new javax.swing.JPasswordField();
        txtRepeatPassword = new javax.swing.JPasswordField();
        checkLocked = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Mantenedor de usuarios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel2.setText("Nombre Completo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel1.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 150, -1));

        jLabel3.setText("Rut :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));
        jPanel1.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 150, -1));

        jLabel4.setText("Nombre Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 150, -1));

        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setText("Repetir Contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        btnListUsers.setText("Listar");
        btnListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUsersActionPerformed(evt);
            }
        });
        jPanel1.add(btnListUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 110, -1));

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 110, -1));

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 110, -1));

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 110, -1));

        btnCreate.setText("Crear");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 150, -1));

        usersList.setColumns(20);
        usersList.setRows(5);
        jScrollPane1.setViewportView(usersList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 410, 180));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, -1));
        jPanel1.add(txtRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, -1));

        checkLocked.setText("Bloqueado/Bloquear");
        jPanel1.add(checkLocked, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String rut, fullname, username, password;
        boolean locked = false;
        User user = null;
        if (!txtRut.getText().equals("")
                && !txtFullName.getText().equals("")
                && !txtUsername.getText().equals("")
                && !txtPassword.getText().equals("")
                && !txtRepeatPassword.getText().equals("")) {
            if (txtPassword.getText().equals(txtRepeatPassword.getText())) {
                rut = txtRut.getText();
                fullname = txtFullName.getText();
                username = txtUsername.getText();
                password = txtPassword.getText();
                locked = checkLocked.isSelected();
                user = new User(username, password, fullname, rut, locked);
                if (UserDAO.update(user)) {
                    clearForm();
                    JOptionPane.showMessageDialog(null, "Usuario Editado Correctamente", "Editar", 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Nombre Usuario ingresado no existe", "Error", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Contraseñas no coinciden", "error", 3);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Todos los Campos", "Validación", 2);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String rut, fullname, username, password;
        boolean locked = false;
        User user = null;
        if (!txtRut.getText().equals("")
                && !txtFullName.getText().equals("")
                && !txtUsername.getText().equals("")
                && !txtPassword.getText().equals("")
                && !txtRepeatPassword.getText().equals("")) {
            if (txtPassword.getText().equals(txtRepeatPassword.getText())) {
                rut = txtRut.getText();
                fullname = txtFullName.getText();
                username = txtUsername.getText();
                password = txtPassword.getText();
                locked = checkLocked.isSelected();
                user = new User(username, password, fullname, rut, locked);
                if (UserDAO.create(user)) {
                    clearForm();
                    JOptionPane.showMessageDialog(null, "Usuario Creado Correctamente", "Creado", 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Nombre Usuario ya existe", "Error", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Contraseñas no coinciden", "error", 3);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Todos los Campos", "Validación", 2);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListUsersActionPerformed
        usersList.setText("");
        UserDAO.all().forEach((user) -> {
            usersList.append(user.toString() + "\n");
        });
    }//GEN-LAST:event_btnListUsersActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String username;
        User user = null;
        if (!txtUsername.getText().equals("")) {
            username = txtUsername.getText();
            user = UserDAO.findUsername(username);
            if (user != null) {
                fillForm(user);
                JOptionPane.showMessageDialog(null, "Usuario Encontrado", "Buscar", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no existe", "Buscar", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese nombre usuario para buscar", "Validación", 2);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String username;
        if (!txtUsername.getText().equals("")) {
            username = txtUsername.getText();
            if (UserDAO.delete(username)) {
                clearForm();
                JOptionPane.showMessageDialog(null, "Usuario eliminado", "Eliminar", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no existe", "Elimnar", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese nombre usuario para buscar", "Validación", 2);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersMaintainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCreate;
    private javax.swing.JToggleButton btnDelete;
    private javax.swing.JToggleButton btnEdit;
    private javax.swing.JToggleButton btnListUsers;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JCheckBox checkLocked;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRepeatPassword;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextArea usersList;
    // End of variables declaration//GEN-END:variables
}
